### ISSUE TITLE
Besoin d'infos pour le schéma

### ISSUE THREAD

**Issue by MelkMerle** [BenjaminPoilve/RapportCSE#1]
Si j'ai bien compris, la fréquence du signal qui contrôlait la vitesse du moteur allait de 10Hz à 10kHz. Qu'en est-il cependant pour le signal haute fréquence qu'on utilisait pour la direction ? quelle était sa fréquence ?

Ah et : est-ce que tu connais le slew rate des AO qu'on a utilisé ?

**Comment by BenjaminPoilve** [comment]
Alors pour les frequences c'est ok? 
La ref de l'ao c'est http://www.farnell.com/datasheets/2003277.pdf d'ou slew rate à . 2.4 V/µs
Au passage c'est quoi un .pages?

**Comment by MelkMerle** [comment]
Les fréquences j’ai donc mis 10-10k pour le BF et 10k pour le HF
Merci pour le slew rate, je change ça asap.

Pages c’est le word d’apple, tu connais pas ? J’ai fait le schéma là-dessus vite fait, et comme c’était pas encore fini je ne l’avais pas encore mis sous format pdf. Mais du coup là maintenant que j’ai fini je vais te le mettre en pdf.

**Comment by BenjaminPoilve** [comment]
C'est parfait pour moi! 
Je fait l'integration dans le README quand c'est ok!

**Comment by MelkMerle** [comment]
Done!
